# Generated by Django 5.1.2 on 2024-10-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('qr_image', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
    ]
